---
driver:
  name: ec2
platforms:
  - name: molecule_redmica_restore_${TIMESTAMP}
    image: ${AMI_ID}
    instance_type: t2.micro
    keypair_name: molecule_redmica_restore_${TIMESTAMP}
    security_group_name: molecule_redmica_restore_${TIMESTAMP}
    vpc_subnet_id: ${VPC_SUBNET_ID}
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_region: ${EC2_REGION}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    local_file_name: ${AWS_S3_OBJECT_NAME}
    s3_bucket: ${AWS_S3_BUCKET_NAME}
    s3_object_name: ${AWS_S3_OBJECT_NAME}
  log: false
  playbooks:
    converge: ../../restore.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - cleanup
    - destroy
