- name: Create user 'git' / git controlling account
  user:
    name: git

- name: Delete existing git repositories
  file:
    path: /var/git
    state: absent

- name: Unarchive git repository data file
  unarchive:
    src: "{{ backup_data_dir }}/{{ git_archive_file }}"
    dest: /var
    owner: git
    group: git
    mode: 0755
    remote_src: yes
