---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            install.yml

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - redmine
          - redmica

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r molecule/requirements.txt

      - name: Set latest AMI image id to environment variables
        run: |
          AMI_ID=$(aws ec2 describe-images \
          --owners "${{ secrets.AMI_OWNER_ID }}" \
          --filters "Name=name,Values=${{ matrix.scenario }}*" \
          --query 'Images[*][CreationDate, ImageId, Name]' \
          --output text | sort -r | awk 'NR==1 {print $2}')
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create environment variables with timestamp for making sure Molecule would create unique AWS resources
        run: |
          TIMESTAMP=$(date --date "9 hours" "+%Y-%m-%d_%H:%M:%S")
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Test with molecule
        run: |
          molecule test --scenario-name ${{ matrix.scenario }}
        env:
          # AMI_ID: sotred in system environment variables
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_S3_OBJECT_NAME: ${{ secrets.AWS_S3_OBJECT_NAME }}
          EC2_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          # TIMESTAMP: sotred in system environment variables

      - name: Show Ansible version
        run: ansible --version

      - name: Show Molecule version
        run: molecule --version

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d7

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: yamllint --version
