---
- name: Delete exisiting Redmine media directory
  ansible.builtin.file:
    path: "{{ redmine_dir }}/files"
    state: absent

- name: Unarchive media data files
  ansible.builtin.unarchive:
    src: "{{ backup_data_dir }}/{{ media_file }}"
    dest: '{{ redmine_dir }}'
    owner: apache
    group: apache
    mode: 0755
    remote_src: yes

- name: Change owner and group of files directory
  ansible.builtin.file:
    path: "{{ redmine_dir }}/files"
    owner: apache
    group: apache
    mode: 0755
    recurse: yes
