- name: Delete exisiting Redmine media directory
  file:
    path: "{{ redmine_dir }}/files"
    state: absent

- name: Unarchive media data files
  unarchive:
    src: "{{ backup_data_dir }}/{{ media_file }}"
    dest: '{{ redmine_dir }}'
    owner: apache
    group: apache
    mode: 0755
    remote_src: yes
